config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  root to: "rooms#index"   
  resources :rooms do
  	collection do
  		post :create_room
  	end
  end
  resources :messages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages
	has_many :users, through: :messages
	validates :name, presence: {message: "Room Name must exist"}
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
    # respond_to do |format|
    #   format.js
    # end
  end

  def show
    @rooms = Room.all
    render 'index'
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create_room
    @room = Room.new(name: params[:room_name])

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path, notice: "Room was successfully created." }
        format.json { render :index, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

 

  private
    def set_room
      @room = Room.find(params[:id])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
  <div class="field">
    <%= text_field_tag 'name', nil,class: 'form-control room_name' %>
  </div>

  <div class="actions mt-3">
    <%= link_to "Add room", nil,remote: true, class: 'btn btn-primary data-btn'%>
  </div>

app/views/rooms/_room_chat.html.erb
<div class="overflow-auto">
<%@rooms.order(id: :desc).each do |room|%>
  <%= link_to room do%>
    <div class="card mb-2" data-spy="scroll">
      <div class="card-body">
        <b><%= room.name%></b><br>
        <small><%= room.users.uniq.count%>member</small>
      </div>
    </div>
  <%end%>  
<%end%>
</div>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div id="room-id" data-room-id="<%= @room.try(:id)%>"%></div>
<div id="user-id" data-user-id="<%= current_user.id%>"%></div>
<div class="container-fluid">
  <div class="row">
    <div class="col-3 mt-4">
      <%= render 'form', room: Room.new%>
      <hr>
      <div class="room-chat overflow-auto" >
        <%= render 'room_chat', room: @room%>
      </div>
    </div>      
    <%if @room.present?%>
    <div class="col-8 mt-4 back-color pt-3">
        <div class="chat-room">
            <div id ="messages" class="overflow-auto">
              <%@room.messages.each do |message|%>
              <div class="content-contanier">
                <div class="message mb-2  <%= 'me' if message.user == current_user%>">
                  <div class="content ">
                    <%= render 'messages/message',message: message%>
                  </div>
                  <div class="author">
                    <%=message.user.username%>
                  </div>
                </div>
              </div>
              <%end%>
            </div>
            <%= render 'messages/form', message:Message.new, room: @room%>
          <%end%>
        </div>
    </div>
  </div>
</div>

app/views/rooms/index.js.erb
$('.room-chat').html("<%= escape_javascript(render partial:  'room_chat', locals: {room: @room} )%>");
$(".room_name").val("")

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>